import { GoogleGenAI, Type } from "@google/genai";
import { RawSchoolData, School, Course, SchoolManagementStatus } from '../types';

// This is a conceptual implementation. In a real application, you would
// pass the image data to the Gemini API. For this example, we return
// hardcoded data that simulates the API's JSON output.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

const MOCK_RAW_DATA: RawSchoolData[] = [
    { codigo: 10638, "NOMBRE COLEGIO": "LICEO 131", CURSO: "1", LETRA: "B", TELEFONO: "28213424", CORREO: "LICEOA131@GMAIL.COM", "NOMBRES DIRECTOR": "PATRICIO ALEJANDRO", "APELLIDO DIRECTOR": "CARRASCO", latitud: -33.73164938, longitud: -70.7430009 },
    { codigo: 10638, "NOMBRE COLEGIO": "LICEO 131", CURSO: "2", LETRA: "D", TELEFONO: "28213424", CORREO: "LICEOA131@GMAIL.COM", "NOMBRES DIRECTOR": "PATRICIO ALEJANDRO", "APELLIDO DIRECTOR": "CARRASCO", latitud: -33.73164938, longitud: -70.7430009 },
    { codigo: 10638, "NOMBRE COLEGIO": "LICEO 131", CURSO: "4", LETRA: "F", TELEFONO: "28213424", CORREO: "LICEOA131@GMAIL.COM", "NOMBRES DIRECTOR": "PATRICIO ALEJANDRO", "APELLIDO DIRECTOR": "CARRASCO", latitud: -33.73164938, longitud: -70.7430009 },
    { codigo: 10640, "NOMBRE COLEGIO": "COLEGIO DE MAIPO", CURSO: "2", LETRA: "D", TELEFONO: "28692818", CORREO: "PAULINA.TORRES@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "PAULINA SOLEDAD", "APELLIDO DIRECTOR": "TORRES", latitud: -33.73442362, longitud: -70.77826756 },
    { codigo: 10640, "NOMBRE COLEGIO": "COLEGIO DE MAIPO", CURSO: "8", LETRA: "A", TELEFONO: "28692818", CORREO: "PAULINA.TORRES@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "PAULINA SOLEDAD", "APELLIDO DIRECTOR": "TORRES", latitud: -33.73442362, longitud: -70.77826756 },
    { codigo: 10642, "NOMBRE COLEGIO": "LICEO POLIVALENTE LOS GUINDOS", CURSO: "1", LETRA: "A", TELEFONO: "28692819", CORREO: "FELICITA.MOLINA@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "EMILIO ERNESTO", "APELLIDO DIRECTOR": "PULGAR", latitud: -33.71270284, longitud: -70.7220688 },
    { codigo: 10642, "NOMBRE COLEGIO": "LICEO POLIVALENTE LOS GUINDOS", CURSO: "3", LETRA: "C", TELEFONO: "28692819", CORREO: "FELICITA.Molina@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "EMILIO ERNESTO", "APELLIDO DIRECTOR": "PULGAR", latitud: -33.71270284, longitud: -70.7220688 },
    { codigo: 10645, "NOMBRE COLEGIO": "LICEO FRANCISCO JAVIER KRUGGER ALVARADO", CURSO: "3", LETRA: "B", TELEFONO: "8216037", CORREO: "LFRAJAKRU@GMAIL.COM;CRISTIAN.FRIAS@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "CRISTIAN PATRICIO", "APELLIDO DIRECTOR": "FRIAS", latitud: -33.76263174, longitud: -70.7678395 },
    { codigo: 10651, "NOMBRE COLEGIO": "ESCUELA LOS ROSALES DEL BAJO", CURSO: "8", LETRA: "A", TELEFONO: "8216165", CORREO: "RDELBAJO@HOTMAIL.COM", "NOMBRES DIRECTOR": "ANDREA RAQUEL", "APELLIDO DIRECTOR": "LAGOS", latitud: -33.71385889, longitud: -70.74442855 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "1", LETRA: "A", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "1", LETRA: "B", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "1", LETRA: "C", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "2", LETRA: "C", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "3", LETRA: "C", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "3", LETRA: "G", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "4", LETRA: "C", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "4", LETRA: "G", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "8", LETRA: "C", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10658, "NOMBRE COLEGIO": "LICEO POLIVALENTE MODERNO CARDENAL CARO", CURSO: "8", LETRA: "D", TELEFONO: "22902300", CORREO: "LICEOCARDENALCARO@LCCBUIN.CL", "NOMBRES DIRECTOR": "GONZALO ANDRES", "APELLIDO DIRECTOR": "LAVAUD", latitud: -33.72792376, longitud: -70.74785372 },
    { codigo: 10662, "NOMBRE COLEGIO": "COLEGIO SAINT MARY COLLEGE", CURSO: "3", LETRA: "D", TELEFONO: "228212084", CORREO: "SAINTMARY@CTCINTERNET.CL", "NOMBRES DIRECTOR": "PURISIMA DEL CARMEN", "APELLIDO DIRECTOR": "SOTO", latitud: -33.72914399, longitud: -70.73969471 },
    { codigo: 16815, "NOMBRE COLEGIO": "COLEGIO PATAGONIA DE BUIN", CURSO: "4", LETRA: "A", TELEFONO: "3196049", CORREO: "COLEGIOPATAGONIABUIN@COLEGIOPATAGONIABUIN.CL", "NOMBRES DIRECTOR": "YURI NELSON", "APELLIDO DIRECTOR": "ROMERO", latitud: -33.738802, longitud: -70.74093499 },
    { codigo: 24719, "NOMBRE COLEGIO": "COLEGIO BUIN", CURSO: "1", LETRA: "A", TELEFONO: "8211448", CORREO: "DIRECCION@COLEGIOBUIN.CL", "NOMBRES DIRECTOR": "ANA MARIA", "APELLIDO DIRECTOR": "GONZALEZ", latitud: -33.741166, longitud: -70.74124999 },
    { codigo: 24836, "NOMBRE COLEGIO": "COLEGIO SAN ISIDRO", CURSO: "3", LETRA: "B", TELEFONO: "23825120", CORREO: "DIRECCION@COLEGIOSANISIDRO.CL", "NOMBRES DIRECTOR": "SIGISFREDO HUMBERTO", "APELLIDO DIRECTOR": "LAGOS", latitud: -33.760725, longitud: -70.74182 },
    { codigo: 25241, "NOMBRE COLEGIO": "COLEGIO SAINT JAMES SCHOOL", CURSO: "3", LETRA: "A", TELEFONO: "8215144", CORREO: "SAINTJAMES.COLEGIO@GMAIL.COM", "NOMBRES DIRECTOR": "REBECA DEL CARMEN", "APELLIDO DIRECTOR": "CONTE", latitud: -33.733354, longitud: -70.75487 },
    { codigo: 25278, "NOMBRE COLEGIO": "COLEGIO CAMPANARIO", CURSO: "2", LETRA: "A", TELEFONO: "8216099", CORREO: "INFO@COLEGIOCAMPANARIO.CL", "NOMBRES DIRECTOR": "OSCAR ARNALDO", "APELLIDO DIRECTOR": "FUENTES", latitud: -33.76028, longitud: -70.73548 },
    { codigo: 25278, "NOMBRE COLEGIO": "COLEGIO CAMPANARIO", CURSO: "4", LETRA: "A", TELEFONO: "8216099", CORREO: "INFO@COLEGIOCAMPANARIO.CL", "NOMBRES DIRECTOR": "OSCAR ARNALDO", "APELLIDO DIRECTOR": "FUENTES", latitud: -33.76028, longitud: -70.73548 },
    { codigo: 25591, "NOMBRE COLEGIO": "LICEO TECNICO PROFESIONAL DE BUIN", CURSO: "1", LETRA: "C", TELEFONO: "28211881", CORREO: "LICEOLBTP@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "FRESIA BERNARDITA", "APELLIDO DIRECTOR": "RAMIREZ", latitud: -33.72136125, longitud: -70.74048198 },
    { codigo: 25591, "NOMBRE COLEGIO": "LICEO TECNICO PROFESIONAL DE BUIN", CURSO: "4", LETRA: "C", TELEFONO: "28211881", CORREO: "LICEOLBTP@CORPORACIONBUIN.CL", "NOMBRES DIRECTOR": "FRESIA BERNARDITA", "APELLIDO DIRECTOR": "RAMIREZ", latitud: -33.72136125, longitud: -70.74048198 },
    { codigo: 25602, "NOMBRE COLEGIO": "ESC. PART. PABLO APOSTOL DE BUIN", CURSO: "1", LETRA: "A", TELEFONO: "28220218", CORREO: "COLEGIO@PABLOAPOSTOLBUIN.CL", "NOMBRES DIRECTOR": "KARIN ANDREA", "APELLIDO DIRECTOR": "SILVA", latitud: -33.72909569, longitud: -70.74678237 },
    { codigo: 25602, "NOMBRE COLEGIO": "ESC. PART. PABLO APOSTOL DE BUIN", CURSO: "2", LETRA: "A", TELEFONO: "28220218", CORREO: "COLEGIO@PABLOAPOSTOLBUIN.CL", "NOMBRES DIRECTOR": "KARIN ANDREA", "APELLIDO DIRECTOR": "SILVA", latitud: -33.72909569, longitud: -70.74678237 },
    { codigo: 25602, "NOMBRE COLEGIO": "ESC. PART. PABLO APOSTOL DE BUIN", CURSO: "3", LETRA: "A", TELEFONO: "28220218", CORREO: "COLEGIO@PABLOAPOSTOLBUIN.CL", "NOMBRES DIRECTOR": "KARIN ANDREA", "APELLIDO DIRECTOR": "SILVA", latitud: -33.72909569, longitud: -70.74678237 },
    { codigo: 25602, "NOMBRE COLEGIO": "ESC. PART. PABLO APOSTOL DE BUIN", CURSO: "8", LETRA: "A", TELEFONO: "28220218", CORREO: "COLEGIO@PABLOAPOSTOLBUIN.CL", "NOMBRES DIRECTOR": "KARIN ANDREA", "APELLIDO DIRECTOR": "SILVA", latitud: -33.72909569, longitud: -70.74678237 },
    { codigo: 26111, "NOMBRE COLEGIO": "ESC. DE PARV. Y ESP. PUKARAY", CURSO: "8", LETRA: "A", TELEFONO: "25179845", CORREO: "PUKARAY@GMAIL.COM", "NOMBRES DIRECTOR": "VICTOR ANDRES", "APELLIDO DIRECTOR": "AGUILERA", latitud: -33.73355183, longitud: -70.74223478 },
    { codigo: 26117, "NOMBRE COLEGIO": "ESCUELA B_X001A__X001A_SICA N 149 SAN MARCEL", CURSO: "2", LETRA: "B", TELEFONO: "32781198", CORREO: "DIRECCIONSANMARCEL@GMAIL.COM", "NOMBRES DIRECTOR": "DANILO JAVIER", "APELLIDO DIRECTOR": "PEREZ", latitud: -33.713862, longitud: -70.74229207 },
    { codigo: 26269, "NOMBRE COLEGIO": "COLEGIO ALTO DEL VALLE", CURSO: "2", LETRA: "B", TELEFONO: "3823598", CORREO: "ADMINISTRACION@ALTODELVALLE.CL", "NOMBRES DIRECTOR": "MARIA ISABEL", "APELLIDO DIRECTOR": "PEREZ", latitud: -33.73157859, longitud: -70.77296766 },
    { codigo: 26482, "NOMBRE COLEGIO": "COLEGIO INGLES SAN JOSE DE LINDEROS", CURSO: "4", LETRA: "A", TELEFONO: "8211670", CORREO: "DIRECCION@COLEGIOINGLESSANJOSEDELINDEROS.COM", "NOMBRES DIRECTOR": "MARCELO ENRIQUE", "APELLIDO DIRECTOR": "ANDRADE", latitud: -33.76234, longitud: -70.74215 },
    { codigo: 26482, "NOMBRE COLEGIO": "COLEGIO INGLES SAN JOSE DE LINDEROS", CURSO: "8", LETRA: "A", TELEFONO: "8211670", CORREO: "DIRECCION@COLEGIOINGLESSANJOSEDELINDEROS.COM", "NOMBRES DIRECTOR": "MARCELO ENRIQUE", "APELLIDO DIRECTOR": "ANDRADE", latitud: -33.76234, longitud: -70.74215 },
    { codigo: 31267, "NOMBRE COLEGIO": "INSTITUTO SAN ALBERTO HURTADO", CURSO: "4", LETRA: "A", TELEFONO: "443069136", CORREO: "COLEGIOST.ISAH@GMAIL.COM", "NOMBRES DIRECTOR": "INGRID VANESSA", "APELLIDO DIRECTOR": "ESSE", latitud: -33.734417, longitud: -70.7564 },
    { codigo: 41773, "NOMBRE COLEGIO": "COLEGIO NOVA TERRA LINDEROS", CURSO: "1", LETRA: "A", TELEFONO: "981580252", CORREO: "DIRECCIONCOLEGIOLINDEROS@GMAIL.COM", "NOMBRES DIRECTOR": "OSCAR ALEJANDRO", "APELLIDO DIRECTOR": "MIRANDA", latitud: -33.76723, longitud: -70.73065 },
    { codigo: 42162, "NOMBRE COLEGIO": "ESCUELA BASICA COLEGIO SAN FERNANDO DE BUIN-ORIE", CURSO: "8", LETRA: "A", TELEFONO: "3819586", CORREO: "SECRETARIA.ORIENTE@SANFERNANDOCOLEGIO.CL", "NOMBRES DIRECTOR": "JORGE ANDRES", "APELLIDO DIRECTOR": "PIZARRO", latitud: -33.73533, longitud: -70.720161 }
];


// FIX: Added and exported `extractSchoolDataFromImage` function as it was missing and referenced in App.tsx.
export const extractSchoolDataFromImage = async (): Promise<RawSchoolData[]> => {
    // In a real application, this function would call the Gemini API
    // with an image and parse the response. For this demo, we use mock data.
    console.log("Usando datos de prueba. En una app real, esto llamaría a la API de Gemini.");
    return Promise.resolve(MOCK_RAW_DATA);
};

// FIX: Added and exported `processRawData` function as it was missing and referenced in App.tsx.
export const processRawData = (rawData: RawSchoolData[]): School[] => {
    const schoolsMap = new Map<number, School>();

    rawData.forEach(rawSchool => {
        const schoolCode = rawSchool.codigo;
        if (!schoolsMap.has(schoolCode)) {
            schoolsMap.set(schoolCode, {
                code: schoolCode,
                name: rawSchool['NOMBRE COLEGIO'],
                phone: rawSchool.TELEFONO,
                email: rawSchool.CORREO,
                director: `${rawSchool['NOMBRES DIRECTOR']} ${rawSchool['APELLIDO DIRECTOR']}`,
                latitude: rawSchool.latitud,
                longitude: rawSchool.longitud,
                courses: [],
                notes: [],
                managementStatus: SchoolManagementStatus.Pending,
            });
        }

        const school = schoolsMap.get(schoolCode)!;
        
        const course: Course = {
            id: `${rawSchool.CURSO}-${rawSchool.LETRA}`,
            level: rawSchool.CURSO,
            letter: rawSchool.LETRA,
        };

        // Avoid adding duplicate courses
        if (!school.courses.some(c => c.id === course.id)) {
            school.courses.push(course);
        }
    });

    return Array.from(schoolsMap.values());
};